[theme]
base = "light"
primaryColor = "#2E75B6"
backgroundColor = "#F2F2F2"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#152B3D"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true

[browser]
gatherUsageStats = false
